# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nU9sIL_qeQzMKgEmlewdUdx-fOJrqaS1
"""

import cv2 as cv

image = cv.imread("background.jpg")
image = cv.resize(image, (1920,1080), interpolation = cv.INTER_AREA)
cv.imwrite("small_background.jpg",image)